server:
  port: 48085
spring:
  application:
    name: QuickStartGatewayMvcService
  config:
    import: optional:polaris
  cloud:
    polaris:
      address: grpc://119.91.66.223:8091
      namespace: default
      enabled: true
      contract:
        exposure: true
        report:
          enabled: true
      stat:
        enabled: true
        port: 28085
    gateway:
      mvc:
        routes:
          - id: QuickstartCallerService
            uri: lb://QuickstartCallerService
            predicates:
              - Path=/QuickstartCallerService/**
            filters:
              - StripPrefix=1


